### ISSUE TITLE
Various drag & drop issues

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#28]
Including but not limited to:

- some sessions cannot be targeted with drag and drop at all
- sometimes after a talk is dropped into a session it cannot be moved again, either to another session or back to unassigned talks
- drag here hints don't always disappear
- from 6/27: after dragging an unassigned talk from left to schedule, cannot move back to left column and can only move into another section/time slot if you first move one talk from the left column into the schedule...wat
- 6/27: drag/drop hint counted as a session, which means when you drop two talks into a session (poss only if dropped above the hint??), you get the warning box a talk before you should

**Comment by kmccurley** [comment]
There were several issues here. I think part of it was fixed by removing the div that was surrounding the {#empty} part. Another part was that you were calling addDrag() twice. When we call drawProgram() and then drawTalks() we should then call addDrag() (and it shouldn't be called anywhere else - particularly not inside drawProgram() or drawTalks()).

**Comment by kaymckelly** [comment]
This variety of bugs was introduced by several things, one of which was calling addDrag() twice within the draw functions. Master is currently working.
